// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Medico
{
    public Medico(string nome, string crm, string especialidade, string email,
        string celular, string endereco)
    {
        Nome = nome;
        Crm = crm;
        Especialidade = especialidade;
        Email = email;
        Celular = celular;
        Endereco = endereco;
        DataCadastro = DateTime.UtcNow;
    }

    public int IdMedico { get; private set; }
    public string Nome { get; private set; }
    public string Crm { get; private set; }
    public string Especialidade { get; private set; }
    public string Email { get; private set; }
    public string Celular { get; private set; }
    public string Endereco { get; private set; }
    public DateTime? DataCadastro { get; private set; }

    public void Update(string nome, string crm, string especialidade, string email, string celular, string endereco)
    {
        Nome = nome;
        Crm = crm;
        Especialidade = especialidade;
        Email = email;
        Celular = celular;
        Endereco = endereco;
    }
}