// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Medico
{
    public int IdMedico { get; private set; }
    public string Nome { get; private set; }
    public string Crm { get; private set; }
    public string Especialidade { get; private set; }
    public string Email { get; private set; }
    public string Celular { get; private set; }
    public string Endereco { get; private set; }
    public DateTime? DataCadastro { get; private set; }
}