// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Paciente
{
    public Paciente(string nome, string cpf, string celular, string email,
        string endereco, DateTime? dataNasc,string tipoSanguineo)
    {
        Nome = nome;
        Cpf = cpf;
        Celular = celular;
        Email = email;
        Endereco = endereco;
        DataNasc = dataNasc;
        TipoSanguineo = tipoSanguineo;

        DataCadastro = DateTime.UtcNow;
    }

    public int IdPaciente { get; private set; }
    public string Nome { get; private set; }
    public string Cpf { get; private set; }
    public string Celular { get; private set; }
    public string Email { get; private set; }
    public string Endereco { get; private set; }
    public DateTime? DataNasc { get; private set; }
    public DateTime? DataCadastro { get; private set; }
    public string TipoSanguineo { get; private set; }

    public void Update(string nome, string cpf, string celular, string email, string endereco, DateTime? dataNasc, string tipoSanguineo)
    {
        Nome = nome;
        Cpf = cpf;
        Celular =celular;
        Email = email;
        Endereco = endereco;
        DataNasc = dataNasc;
        TipoSanguineo = tipoSanguineo;
    }
}