// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Servico
{
    public int IdServico { get; private set; }
    public string NomeServico { get; private set; }
    public string Descricao { get; private set; }
    public decimal? Preco { get; private set; }
    public string Duracao { get; private set; }
}