// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Servico
{
    public Servico(string nomeServico, string descricao, decimal? preco, string duracao)
    {
        NomeServico = nomeServico;
        Descricao = descricao;
        Preco = preco;
        Duracao = duracao;
    }
    public int IdServico { get; private set; }
    public string NomeServico { get; private set; }
    public string Descricao { get; private set; }
    public decimal? Preco { get; private set; }
    public string Duracao { get; private set; }

    public void Update(string nomeServico, string descricao, decimal? preco, string duracao)
    {
        NomeServico = nomeServico;
        Descricao = descricao;
        Preco = preco;
        Duracao = duracao;
    }
}