// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicaMedica.Core.Entidades;

public partial class Usuario
{
    public Usuario(int idUsuario, string nome, string email, string senha, string papel)
    {
        IdUsuario = idUsuario;
        Nome = nome;
        Email = email;
        Senha = senha;
        Papel = papel;
    }
    public int IdUsuario { get; private set; }
    public string Nome { get; private set; }
    public string Email { get; private set; }
    public string Senha { get; private set; }
    public string Papel { get; private set; }
}